# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x68a3963D2fE3427cfD044806B40AF41feCaae845"
    chainName: sei
    connections:
      - token: ethereum|ethereum|0x1Ae0F9913B9277615A94eb78D4D438E708F67571
    decimals: 18
    name: fastUSD
    standard: EvmHypSynthetic
    symbol: fastUSD
  - addressOrDenom: "0x1Ae0F9913B9277615A94eb78D4D438E708F67571"
    chainName: ethereum
    collateralAddressOrDenom: "0x15700B564Ca08D9439C58cA5053166E8317aa138"
    connections:
      - token: ethereum|sei|0x68a3963D2fE3427cfD044806B40AF41feCaae845
    decimals: 18
    name: deUSD
    standard: EvmHypCollateral
    symbol: deUSD
